feat: w w
Signed-off-by: hxtree <matthew.heroux@gmail.com>

diff --git a/common/git-hooks/commit-msg b/common/git-hooks/commit-msg
--- a/common/git-hooks/commit-msg
+++ b/common/git-hooks/commit-msg
@@ -18,16 +18,31 @@
 
 # This example enforces that commit message should contain a minimum amount of
 # description text.
-commit_message="$1"
 
-if [ $(cat $1 | wc -w) -lt 3 ]; then
+node common/scripts/install-run-rush.js commitlint --edit $1
+exit 1
+
+COMMIT_MESSAGE="$1"
+
+echo "$COMMIT_MESSAGE"
+
+if [ $(cat $COMMIT_MESSAGE | wc -w) -lt 3 ]; then
   echo ""
   echo "Invalid commit message: The message must contain at least 3 words."
   exit 1
 fi
 
-# use git-conventional-commits, see https://github.com/qoomon/git-conventional-commits
-echo "$commit_message" | commitlint || true
+exit 1
+
+# Run commitlint with the commit message as an argument
+echo "${COMMIT_MESSAGE}" | commitlint
+
+if [ $? -ne 0 ]; then
+  echo "commitlint failed. Exiting..."
+  exit 1
+else
+  echo "commitlint passed."
+fi
 
 # enforce DCO https://wiki.linuxfoundation.org/dco
 NAME=$(git config user.name)
